[package]
name = "async_ash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37"
tracing = "0.1"
futures-util = "0.3"
async_ash_macro = { path = "./async_ash_macro" }
vk-mem = { git = "https://github.com/dust-engine/vk-mem-rs" }
blocking = "1.2"
pin-project = "1.0"

[workspace]
members = [
    "async_ash_macro",
]
