[package]
name = "async_ash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_ash_core = { path = "./core" }
async_ash_alloc = { path = "./alloc" }

[workspace]
members = [
    "macro",
    "core",
    "alloc"
]


[dev-dependencies]
image = "0.24"
winit = "0.28"
futures = "*"
reqwest = { version = "*", features = ["blocking"] }
