[package]
name = "rhyolite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "crates/*",
]

[dependencies]
crossbeam-channel = "0.5"
crossbeam-queue = "0.3"
bevy = { version = "0.13", default-features = false, features=["multi-threaded","wayland", "x11", "bevy_asset"] }
ash = "0.37"
tracing = "0.1"
cstr = "0.2"
thread_local = "1"
winit = { version = "0.29", default-features = false, features = ["rwh_06"] }
raw-window-handle = "0.6"
glam = "0.24"
arrayvec = "0.7"
itertools = "0.12"
vk-mem = "0.3"
thiserror = "1.0"
playout = { path = "../playout" }

[patch.crates-io]
bevy = { path = "../bevy" }

[dev-dependencies]
rhyolite_egui = { path = "crates/egui" }
