[package]
name = "rhyolite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rhyolite-core = { path = "./core" }

[workspace]
members = [
    "macro",
    "core"
]


[dev-dependencies]
image = "0.24"
winit = "0.28"
futures = "*"
reqwest = { version = "*", features = ["blocking"] }
