[package]
name = "async_ash_alloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vk-mem = { git = "https://github.com/dust-engine/vk-mem-rs" }
async_ash_core = { path = "../core" }
