[package]
name = "rhyolite_rtx"
version = "0.1.0"
edition = "2021"

[dependencies]
rhyolite = { path = "../../" }
bevy = { version = "0.14.0", default-features = false }
bytemuck = "1.15"
itertools = "0.12"
smallvec = "1.6"
nonmax = "0.5.3"
