[package]
name = "rhyolite-bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rhyolite = { path = "../core" }
bevy_app = { git = "https://github.com/bevyengine/bevy.git", rev = "f7fbfaf9c72035e98c6b6cec0c7d26ff9f5b1c82" }
bevy_tasks = { git = "https://github.com/bevyengine/bevy.git", rev = "f7fbfaf9c72035e98c6b6cec0c7d26ff9f5b1c82" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy.git", rev = "f7fbfaf9c72035e98c6b6cec0c7d26ff9f5b1c82" }
bevy_window = { git = "https://github.com/bevyengine/bevy.git", rev = "f7fbfaf9c72035e98c6b6cec0c7d26ff9f5b1c82" }


[dev-dependencies]
image = "0.24"
reqwest = { version = "*", features = ["blocking"] }
bevy_log = { git = "https://github.com/bevyengine/bevy.git", rev = "f7fbfaf9c72035e98c6b6cec0c7d26ff9f5b1c82" }
bevy_input = { git = "https://github.com/bevyengine/bevy.git", rev = "f7fbfaf9c72035e98c6b6cec0c7d26ff9f5b1c82" }
bevy_core = { git = "https://github.com/bevyengine/bevy.git", rev = "f7fbfaf9c72035e98c6b6cec0c7d26ff9f5b1c82" }
bevy_hierarchy = { git = "https://github.com/bevyengine/bevy.git", rev = "f7fbfaf9c72035e98c6b6cec0c7d26ff9f5b1c82" }
bevy_transform = { git = "https://github.com/bevyengine/bevy.git", rev = "f7fbfaf9c72035e98c6b6cec0c7d26ff9f5b1c82" }
bevy_winit = { git = "https://github.com/bevyengine/bevy.git", rev = "f7fbfaf9c72035e98c6b6cec0c7d26ff9f5b1c82" }
bevy_time = { git = "https://github.com/bevyengine/bevy.git", rev = "f7fbfaf9c72035e98c6b6cec0c7d26ff9f5b1c82" }
bevy_diagnostic = { git = "https://github.com/bevyengine/bevy.git", rev = "f7fbfaf9c72035e98c6b6cec0c7d26ff9f5b1c82" }
