[package]
name = "rhyolite_egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bevy_egui]
version = "0.25"
default_features = false
features = ["manage_clipboard", "open_url", "default_fonts"]

[dependencies]
bevy = { version = "0.13", default-features = false }
rhyolite = { path = "../../" }
playout_macro = { path = "../../../playout/macro" }
bytemuck = "1.14"
